services:
  postgres:
    container_name: eksamen-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passord01
      POSTGRES_DB: postgres
    ports:
      - 6543:5432
    volumes:
      - eksamen-postgres:/var/lib/postgresql/data/

volumes:
  eksamen-postgres: